apiVersion: apps/v1
kind: Deployment
metadata:
  name: karl-portfolio
  labels:
    app: karl-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karl-portfolio
  template:
    metadata:
      labels:
        app: karl-portfolio
    spec:
      nodeSelector:
        "kubernetes.io/hostname": ubuntu
      containers:
        - name: karl-portfolio
          image: karlmabs/karl-portfolio:latest
          ports:
            - containerPort: 3000
      restartPolicy: Always
