apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: karl-portfolio-ingress
  namespace: karl-portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # Uncomment the next line if you have cert-manager installed
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: karlmabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karl-portfolio
                port:
                  number: 80
    - host: www.karlmabs.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: karl-portfolio
                port:
                  number: 80
  # Uncomment for SSL/TLS with cert-manager
  # tls:
  # - hosts:
  #   - karlmabs.com
  #   - www.karlmabs.com
  #   secretName: karlmabs-tls
